### ISSUE TITLE
Installation nor working on 

### ISSUE THREAD

**Issue by flreinhard** [gnl42/Bracketeer2#2]
First: thank you for your time updating bracketeer!

I installed your new version on eclipse 4.5.2 but it does not work. On the logs i see two error messages. Both stating "FrameworkEvent ERROR". One is coming from pluin me.glindholm.plugin.bracketeer.CDT and one from me.glindholm.plugin.bracketeer.core.

Any idea what's wrong there?

Stack Trace:
```
org.osgi.framework.BundleException: Could not resolve module: me.glindholm.plugin.bracketeer2.CDT [585]
  Unresolved requirement: Require-Bundle: me.glindholm.plugin.bracketeer2.core
    -> Bundle-SymbolicName: me.glindholm.plugin.bracketeer2.core; bundle-version="2.0.0.202401072154"; singleton:="true"
       me.glindholm.plugin.bracketeer2.core [586]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=17))"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```
Session data:
```
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product com.arm.ds.altera
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product com.arm.ds.altera
```

```
org.osgi.framework.BundleException: Could not resolve module: me.glindholm.plugin.bracketeer2.core [586]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=17))"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

```
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product com.arm.ds.altera
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product com.arm.ds.altera
```

**Comment by sebthom** [comment]
Your Eclipse version is like 8 years too old. This plugin targets Eclipse 2023-09 aka 4.29 (which requires Java 17).

You are running Eclipse Mars using Java 8 which was initially released in 2015.

You could try the original plugin from https://github.com/chookapp/Bracketeer

**Comment by flreinhard** [comment]
Thank you for the feedback. I'll try that next week.

Unfortunately, eclipse is being packaged by vendors for several embedded development studios in not very recent versions. So i'm not free to update. Just some examples of one i have installed on my machine:
- Infineon Dave
- Texas instruments Code Composer Studio
- Arm DS-5
- Intel (former Altera) NiosII SoC EDS.

I'd appreciate support for older eclipse/java versions (I've no idea what effort this means), since some user don't have a choice to install a newer eclipse version.

So feel free to close with "won't fix" if it won't happen :)
